// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package cn.javayong.idgenerator.proto;

public interface IdResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sharding.IdResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 id = 3;</code>
   * @return The id.
   */
  long getId();
}
