// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package cn.javayong.idgenerator.proto;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sharding.IdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 定义请求消息的字段
   * </pre>
   *
   * <code>string shardingKey = 1;</code>
   * @return The shardingKey.
   */
  java.lang.String getShardingKey();
  /**
   * <pre>
   * 定义请求消息的字段
   * </pre>
   *
   * <code>string shardingKey = 1;</code>
   * @return The bytes for shardingKey.
   */
  com.google.protobuf.ByteString
      getShardingKeyBytes();
}
